config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stocks
  root "stocks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @gid = "---"
    @name = "---"
    @todayStartPri = "---"
    @yestodEndPri = "---"
    @nowPri = "---"
    @todayMax = "---"
    @todayMin = "---"
    @increase = "---"
    @increPer = "---"
    @traNumber = "---"
    @traAmount = "---"
    @gopicture
    if params[:stocknumber]
      response = RestClient.get "http://web.juhe.cn:8080/finance/stock/hs", :params => { :gid => "sh" + params[:stocknumber], :key => JUHE_CONFIG["api_key"] }
      data = JSON.parse(response.body)
      if data["resultcode"] == "200"
        @gid = data["result"][0]["data"]["gid"].to_s
        @name = data["result"][0]["data"]["name"]
        @todayStartPri = data["result"][0]["data"]["todayStartPri"]
        @yestodEndPri = data["result"][0]["data"]["yestodEndPri"]
        @nowPri = data["result"][0]["data"]["nowPri"]
        @todayMax = data["result"][0]["data"]["todayMax"]
        @todayMin = data["result"][0]["data"]["todayMin"]
        @increase = data["result"][0]["data"]["increase"]
        @increPer = data["result"][0]["data"]["increPer"]
        @traNumber = data["result"][0]["data"]["traNumber"]
        @traAmount = data["result"][0]["data"]["traAmount"]
        @gopicture = data["result"][0]["gopicture"]["monthurl"]
      else
        response = RestClient.get "http://web.juhe.cn:8080/finance/stock/hs", :params => { :gid => "sz" + params[:stocknumber], :key => JUHE_CONFIG["api_key"], :type => 1 }
        data = JSON.parse(response.body)
        if data["resultcode"] == "200"
          @gid = data["result"][0]["data"]["gid"]
          @name = data["result"][0]["data"]["name"]
          @todayStartPri = data["result"][0]["data"]["todayStartPri"]
          @yestodEndPri = data["result"][0]["data"]["yestoEndPri"]
          @nowPri = data["result"][0]["data"]["nowPri"]
          @todayMax = data["result"][0]["data"]["todayMax"]
          @todayMin = data["result"][0]["data"]["todayMin"]
          @increase = data["result"][0]["data"]["increase"]
          @increPer = data["result"][0]["data"]["increPer"]
          @traNumber = data["result"][0]["data"]["traNumber"]
          @traAmount = data["result"][0]["data"]["traAmount"]
          @gopicture = data["result"][0]["gopicture"]["monthurl"]
        else
          response = RestClient.get "http://web.juhe.cn:8080/finance/stock/hk", :params => { :num => params[:stocknumber], :key => JUHE_CONFIG["api_key"]}
          data = JSON.parse(response.body)
          if data["resultcode"] == "200"
            @gid = data["result"][0]["data"]["gid"]
            @name = data["result"][0]["data"]["name"]
            @todayStartPri = data["result"][0]["data"]["openpri"]
            @yestodEndPri = data["result"][0]["data"]["formpri"]
            @nowPri = data["result"][0]["data"]["lastestpri"]
            @todayMax = data["result"][0]["data"]["maxpri"]
            @todayMin = data["result"][0]["data"]["minpri"]
            @increase = data["result"][0]["data"]["uppic"]
            @increPer = data["result"][0]["data"]["limit"]
            @traNumber = data["result"][0]["data"]["traNumber"]
            @traAmount = data["result"][0]["data"]["traAmount"]
            @gopicture = data["result"][0]["gopicture"]["monthurl"]
          else
            response = RestClient.get "http://web.juhe.cn:8080/finance/stock/usa", :params => { :gid => params[:stocknumber], :key => JUHE_CONFIG["api_key"]}
            data = JSON.parse(response.body)
            if data["resultcode"] == "200"
              @gid = data["result"][0]["data"]["gid"]
              @name = data["result"][0]["data"]["name"]
              @todayStartPri = data["result"][0]["data"]["openpri"]
              @yestodEndPri = data["result"][0]["data"]["formpri"]
              @nowPri = data["result"][0]["data"]["lastestpri"]
              @todayMax = data["result"][0]["data"]["maxpri"]
              @todayMin = data["result"][0]["data"]["minpri"]
              @increase = data["result"][0]["data"]["uppic"]
              @increPer = data["result"][0]["data"]["limit"]
              @traNumber = data["result"][0]["data"]["traAmount"]
              @traAmount = "---"
              @gopicture = data["result"][0]["gopicture"]["monthurl"]
            end
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1 class="text-center">股票查询</h1>
<div class="container">
  <div class="container-fluid">
    <br />
    <div class="col-md-4">
    </div>
    <div class="col-md-4 .center-block">
      <%= form_tag stocks_path, :method => :get do %>
        <%= label_tag "请输入要查询的股票："%>
        <br />
        <%= text_field_tag :stocknumber, "", class: 'form-control', placeholder: "股票代码" %>
        <br />
        <%= submit_tag "Submit", class: "btn btn-primary center-block" %>
      <% end %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  <hr />
  <div class="container-fluid">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>股票编号</th>
          <th>股票名称</th>
          <th>今日开盘价</th>
          <th>昨日收盘价</th>
          <th>当前价格</th>
          <th>今日最高价</th>
          <th>今日最低价</th>
          <th>涨跌额</th>
          <th>涨跌百分比</th>
          <th>成交量</th>
          <th>成交金额</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @gid %></td>
          <td><%= @name %></td>
          <td><%= @todayStartPri %></td>
          <td><%= @yestodEndPri %></td>
          <td><%= @nowPri %></td>
          <td><%= @todayMax %></td>
          <td><%= @todayMin %></td>
          <td><%= @increase %></td>
          <td><%= @increPer %></td>
          <td><%= @traNumber %></td>
          <td><%= @traAmount %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <% if @gopicture %>
  <div class="container-fluid center-block">
    <%= image_tag @gopicture, class: "center-block", alt: "MyInc Logo" %>
  </div>
  <% end %>
</div>